name: Pull and Build Docker Image

on:
  workflow_dispatch:
    inputs:
       
      dockerimage-registry:
          description: 'Image Registry '
          required: false
          type: string
       
      docker-image:
          description: 'Docker Image Name '
          required: true
          type: string
    
       
jobs:
  pull-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Buildx Pull and Build
        uses: djbender/docker-buildx-pull-or-build@v0.3
        with:
            docker_username: ${{ secrets.DOCKER_HUB_USERNAME }}
            docker_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
            docker_registry: ${{ inputs.docker-registry }}
            image: ${{inputs.docker-image}}