name: Let's Build Go with Docker ( matrix strategy)

on:
  workflow_dispatch:
    inputs:
      dockerimage-name:
          description: 'Docker Image Name '
          required: true
          type: string

jobs:
 build:
     strategy:
      matrix:
        os: [ ubuntu-20.04 , ubuntu-18.04]
        # image_tag: [1.0.1 , 2.0.1, 3.0.1 ]
        go-version: [1.15, 1.16]
     runs-on: ${{ matrix.os }}

 steps:
  - uses: actions/checkout@v2
    name: Check out code

  - uses: mr-smithers-excellent/docker-build-push@v5
    name: Build & push Docker image
    with:
      image: repo/image
      tags: v1, latest
  
      dockerfile: ./Dockerfile
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}



