name: Pull and Run Docker Image

on:
  workflow_dispatch:
    inputs:
       
 
       
      docker-image:
          description: 'Docker Image Name '
          required: true
          type: string
    
       
jobs:
  pull-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Buildx Pull and Run
        run: |
              docker pull ${{inputs.docker-image}}
              docker run  ${{inputs.docker-image}}
        
        





