

name: Pull and Run Docker Image

on:
  workflow_dispatch:
    inputs:
       
      dockerimage-registry:
          description: 'Image Registry '
          required: false
          type: string
       
      docker-image:
          description: 'Docker Image Name '
          required: true
          type: string
    
       
jobs:
  pull-and-build:
    runs-on: ubuntu-latest
    steps:
        - uses: mosteo-actions/docker-run@v1
          with:
             image: ${{ inputs.docker-image }}
             command: uname -a
